# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "jitsu"
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ilkka Laukkanen"]
  s.date = "2013-07-29"
  s.description = "Jitsu is a frontend or meta build system for Ninja\n(http://github.com/martine/ninja), a lightning-fast but\nin itself (and by design) feature-poor build system.\nJitsu reads project descriptions and generates Ninja\nbuildfiles.\n"
  s.email = "ilkka.s.laukkanen@gmail.com"
  s.executables = ["jitsu"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".autotest",
    ".document",
    ".rspec",
    ".rvmrc",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/jitsu",
    "cucumber.yml",
    "features/jitsu.feature",
    "features/step_definitions/jitsu_steps.rb",
    "features/support/env.rb",
    "features/support/hooks.rb",
    "jitsu.gemspec",
    "lib/jitsu.rb",
    "lib/jitsu/errors.rb",
    "lib/schema.yaml",
    "spec/jitsu_spec.rb",
    "spec/spec_helper.rb",
    "tests.watchr"
  ]
  s.homepage = "http://github.com/ilkka/jitsu"
  s.licenses = ["GPLv3"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Meta build system for Ninja"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<trollop>, ["~> 2.0"])
      s.add_runtime_dependency(%q<kwalify>, ["~> 0.7"])
      s.add_development_dependency(%q<rspec>, ["~> 2.14"])
      s.add_development_dependency(%q<yard>, ["~> 0.8"])
      s.add_development_dependency(%q<cucumber>, ["~> 1.3"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8"])
    else
      s.add_dependency(%q<trollop>, ["~> 2.0"])
      s.add_dependency(%q<kwalify>, ["~> 0.7"])
      s.add_dependency(%q<rspec>, ["~> 2.14"])
      s.add_dependency(%q<yard>, ["~> 0.8"])
      s.add_dependency(%q<cucumber>, ["~> 1.3"])
      s.add_dependency(%q<jeweler>, ["~> 1.8"])
    end
  else
    s.add_dependency(%q<trollop>, ["~> 2.0"])
    s.add_dependency(%q<kwalify>, ["~> 0.7"])
    s.add_dependency(%q<rspec>, ["~> 2.14"])
    s.add_dependency(%q<yard>, ["~> 0.8"])
    s.add_dependency(%q<cucumber>, ["~> 1.3"])
    s.add_dependency(%q<jeweler>, ["~> 1.8"])
  end
end

